import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Personal To-Do List",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={
					inter.className +
					" " +
					"bg-[url('/TaskVault_Background_Image.jpg')] bg-repeat bg-opacity-25"
				}
			>
				{children}
			</body>
		</html>
	);
}
